package vehicle

import (
	"go-simulate-a-city/sim/engine/resource"

	"github.com/go-gl/mathgl/mgl32"
)

type Vehicle struct {
	VehicleType string

	// Autogenerated
	Color mgl32.Vec3

	Cargo resource.ResourceAmount
}
