package vehicle

import (
	"go-simulate-a-city/sim/core/cmap"
	"go-simulate-a-city/sim/engine/resource"

	"github.com/go-gl/mathgl/mgl32"
)

type Vehicle struct {
	VehicleType string
	Length      float32

	// Autogenerated
	Color mgl32.Vec3

	Cargo resource.ResourceAmount
}

type VehicleManager struct {
	vehicles *cmap.Map
}

func NewVehicleManager() *VehicleManager {
	manager := &VehicleManager{
		vehicles: cmap.NewMap()}

	return manager
}
