package vehicle

import (
	"sim/core/cmap"
	"sim/engine/resource"

	"github.com/go-gl/mathgl/mgl32"
)

type Vehicle struct {
	VehicleType string
	Length      float32

	// Autogenerated
	Color mgl32.Vec3

	Cargo resource.ResourceAmount
}

func NewVehicle() *Vehicle {
	return &Vehicle{
		Length: 10.0}
}

type VehicleManager struct {
	vehicles *cmap.Map
}

func NewVehicleManager() *VehicleManager {
	manager := &VehicleManager{
		vehicles: cmap.NewMap()}

	return manager
}

func (v *VehicleManager) NewVehicle() (*Vehicle, int64) {
	vehicle := NewVehicle()
	vehicleId := v.vehicles.IterativeAdd(vehicle)
	return vehicle, vehicleId
}
